name: telc_result_checker
description: A server app using the shelf package and Docker.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dependencies:
  # Utility
  args: ^2.4.0

  # Network
  http: ^1.2.2

  # Logger
  l: ^5.0.0

dev_dependencies:
  # Linting
  lints: ^5.1.1

  # Testing
  test: any
