name: owlistic
description: Owlistic Bot checks results.telc.net and notifies you when your B2 Beruf certificate is online.
version: 0.0.1
repository: https://github.com/dened/owlistic
issue_tracker: https://github.com/dened/owlistic/issues
publish_to: none # No publishing, this is a Docker image

environment:
  sdk: ^3.5.4

dependencies:
  # Annotation
  json_annotation: ^4.9.0
  meta: ^1.16.0

  # Utility
  args: ^2.6.0
  collection: ^1.19.1
  path: ^1.9.1
  intl: ^0.20.2

  # Network
  http: ^1.2.2

  # Logger
  l: ^5.0.0

  # Database (SQLite)
  drift: ^2.25.1


dev_dependencies:
  # Linting
  lints: ^5.1.1

  # Testing
  test: any
  mockito: ^5.4.4

  # Code generation
  build_runner: ^2.4.15
  drift_dev: ^2.25.2
  json_serializable: ^6.9.5 
  intl_translation: ^0.20.1
